### ISSUE TITLE
Conflict 

### ISSUE THREAD

**Issue by uitalo** [ankitest/anki-musthave-addons-by-ankitest#1]
It's a very  good idea, but there are an conflict with "Power format pack: Markdown, code blocks, lists, tables, syntax highlight & more". 

After install your plugin, Power Format not more load.

**Comment by ankitest** [comment]
First Aids: just remove _Alternative hotkeys to cloze selected text in Add or Editor window_ and restart Anki.

**Comment by ankitest** [comment]
Solved. You can download new edition of add-on **2074653746** or _Alternative hotkeys to cloze selected text in Add or Editor window_

**Comment by uitalo** [comment]
Thank you, now is ok!

**Comment by ankitest** [comment]
Fixed.
