### ISSUE TITLE
How to creak beautiful math formula in anki?

### ISSUE THREAD

**Issue by Juddd** [ankitest/anki-musthave-addons-by-ankitest#21]
(I'm sorry to creat such a issues,but I don't know how to contact you in other way.)How to creak beautiful math formula as your sample image in anki?What implement you use?
![](http://savepic.ru/9676050.png)

**Comment by ankitest** [comment]
[• Later not now button](https://ankiweb.net/shared/info/777151722), right?  
It is some shared deck on screenshot, I don't remember exactly which one, *pardonne moi*.  
But there was simple jpg, maybe from some pdf.  
You can use LaTeX with Anki, but I never gave it a try.

**Comment by Juddd** [comment]
@ankitest Latex is a bad choice in Anki.Thank all the same.:)
