### ISSUE TITLE
Promt and set days interval new/learning

### ISSUE THREAD

**Issue by NSBum** [ankitest/anki-musthave-addons-by-ankitest#22]
There is a use-case where setting the interval on new/learning cards makes sense.

I have a handful of older unidirectional notes that I am upgrading to bidirectional note types. So now I have numerous cards with the new direction. Since I know the forward direction well on these old notes, the reverse is also easy as well. Yet now I cannot change the ease and interval to approximately match the original forward card.

For example old note type only had:
[picture of plate] -> тарелка (ease 250%, interval 1.8y)

The new note type has two cards:
[picture of plate] -> тарелка (ease 250%, interval 1.8y)
тарелка -> [picture of plate] (ease 130%, new)

Now that the add-on no longer permits setting ease and interval on new/learning cards, I'm stuck with seeing this card until it matures. Any chance of bringing back the ability to set ease/interval on any note regardless of maturity?

**Comment by ankitest** [comment]
No chance. When you could change ease factor and interval on new and learning cards — it was a misconception bug, cause new and learning cards have no interval and ease % at all, learning cards have just steps, not intervals. 

You can use Browse - select your new direction cards - Reschedule... - Place in review queue with interval between - your approximate intervals in days. Your new and learning cards become review ones, and then you can apply addon to them.

**Comment by NSBum** [comment]
I'll have to give the suggested method a try. That said, although I understand the conceptual inconsistency that the previous code posed, I did not notice any unusual behaviours from Anki on account of it.

**Comment by ankitest** [comment]
Then feel free to use [old version from github.](https://raw.githubusercontent.com/ankitest/anki-musthave-addons-by-ankitest/f4c9b102eb4c67f20e54b513382f597efd4d2ba0/_Prompt_and_set_days_interval_and_card_ease.py)
