### ISSUE TITLE
Mac ?

### ISSUE THREAD

**Issue by JavaChip93** [ankitest/anki-musthave-addons-by-ankitest#24]
Hi, I can't seem to make the ''Edit sound and images'' add-on work on Mac. Is there some trick that I maybe missed?
Thanks 👍

**Comment by ankitest** [comment]
Sorry, I have no Mac at all.  
You can try to customise opening commands on your own manners,  
look at lines 92-94  
https://github.com/ankitest/anki-musthave-addons-by-ankitest/blob/master/_Edit_Audio_Images.py#L92-L94

**Comment by JavaChip93** [comment]
Thanks for the fast answer.
I have a basic coding knowledge I guess but that's about it, I wouldn't understand how to customise this if I wanted to. Not a technician, just a regular student :) 
Thanks anyway
