### ISSUE TITLE
Editor fontsize

### ISSUE THREAD

**Issue by GitHub01945** [ankitest/anki-musthave-addons-by-ankitest#26]
Hi, I created the original thread: https://anki.tenderapp.com/discussions/add-ons/7385-increase-text-size-for-card-types-editor

I was wondering if there is a way to change the font of, or, increase the size of, text in the: Tags bar; Add, Info, Mark, ... menu; button labels; field labels; window that displays decks?

**Comment by ankitest** [comment]
Yes, there is just the same way, as it is already done with other elements. You can define individual font family, size, bold, italic, color, background color for any element in Anki.

**Comment by GitHub01945** [comment]
How would I locate the name of a particular element?

**Comment by ankitest** [comment]
Search by the source code.

**Comment by GitHub01945** [comment]
The source code of Anki?

Which files should I search? What kind of query would display relevant results?

**Comment by ankitest** [comment]
Sorry, teaching programming is beyond the scope of support I can provide here.

**Comment by GitHub01945** [comment]
Do you accept feature requests?
Could the ability to modify text attributes of some additional elements be added to a future version?
